package com.example.myapplication

public class LanguageDataStore {

    fun getLangaugeCodeByLangKey(languageKey : String) : String{
        var value = this.getSupportedLanguageByRecognizer()[languageKey]
        if(value != null) return value else return ""
    }
    fun getSupportedLanguageByRecognizer() : HashMap<String, String> {

        var hashMap : HashMap<String, String>
                = HashMap<String, String> ()
        hashMap.put("English, US","en_US")
        hashMap.put("English, Australia","en_AU")
        hashMap.put("English, Britain","en_GB")
        hashMap.put("English, Canada","en_CA")
        hashMap.put("English, New Zealand","en_NZ")
        hashMap.put("English, Singapore","en_SG")
        hashMap.put("English, India","en_IN")
        hashMap.put("English, Ireland","en_IE")
        hashMap.put("English, Zimbabwe","en_ZA")
        hashMap.put("German, Germany","de_DE")
        hashMap.put("Chinese, PRC","zh_CN")
        hashMap.put("Chinese, Taiwan","zh_TW")
        hashMap.put("Czech, Czech Republic","cs_CZ")
        hashMap.put("Dutch, Belgium","nl_BE")
        hashMap.put("Dutch, Netherlands","nl_NL")
        hashMap.put("French, Belgium","fr_BE")
        hashMap.put("French, Canada","fr_CA")
        hashMap.put("French, France","fr_FR")
        hashMap.put("French, Switzerland","fr_CH")
        hashMap.put("German, Austria","de_AT")
        hashMap.put("German, Liechtenstein","de_LI")
        hashMap.put("German, Switzerland","de_CH")
        hashMap.put("Italian, Italy","it_IT")
        hashMap.put("Italian, Switzerland","it_CH")
        hashMap.put("Japanese","ja_JP")
        hashMap.put("Korean","ko_KR")
        hashMap.put("Polish","pl_PL")
        hashMap.put("Russian","ru_RU")
        hashMap.put("Spanish","es_ES")
        hashMap.put("Arabic, Egypt","ar_EG")
        hashMap.put("Arabic, Israel","ar_IL")
        hashMap.put("Bulgarian, Bulgaria","bg_BG")
        hashMap.put("Catalan, Spain","ca_ES")
        hashMap.put("Croatian, Croatia","hr_HR")
        hashMap.put("Danish, Denmark","da_DK")
        hashMap.put("Finnish, Finland","fi_FI")
        hashMap.put("Greek, Greece","el_GR")
        hashMap.put("Hebrew, Israel","iw_IL")
        hashMap.put("Hindi, India","hi_IN")
        hashMap.put("Hungarian, Hungary","hu_HU")
        hashMap.put("Indonesian, Indonesia","in_ID")
        hashMap.put("Latvian, Latvia","lv_LV")
        hashMap.put("Lithuanian, Lithuania","lt_LT")
        hashMap.put("Norwegian-Bokmol, Norway","nb_NO")
        hashMap.put("Portuguese, Brazil","pt_BR")
        hashMap.put("Portuguese, Portugal","pt_PT")
        hashMap.put("Romanian, Romania","ro_RO")
        hashMap.put("Serbian","sr_RS")
        hashMap.put("Slovak, Slovakia","sk_SK")
        hashMap.put("Slovenian, Slovenia","sl_SI")
        hashMap.put("Spanish, US","es_US")
        hashMap.put("Swedish, Sweden","sv_SE")
        hashMap.put("Tagalog, Philippines","tl_PH")
        hashMap.put("Thai, Thailand","th_TH")
        hashMap.put("Turkish, Turkey","tr_TR")
        hashMap.put("Ukrainian, Ukraine","uk_UA")
        hashMap.put("Vietnamese, Vietnam","vi_VN")

        return hashMap;
    }

    fun getSupportedLanguageByGoogle(): HashMap<String, String> {
        var hashMap : HashMap<String, String>
                = HashMap<String, String> ()
        hashMap.put("English, US","en")
        hashMap.put("English, Australia","en")
        hashMap.put("English, Britain","en")
        hashMap.put("English, Canada","en")
        hashMap.put("English, New Zealand","en")
        hashMap.put("English, Singapore","en")
        hashMap.put("English, India","en")
        hashMap.put("English, Ireland","en")
        hashMap.put("English, Zimbabwe","en")
        hashMap.put("German, Germany","de")
        hashMap.put("Chinese, PRC","zh")
        hashMap.put("Chinese, Taiwan","zh")
        hashMap.put("Czech, Czech Republic","cs")
        hashMap.put("Dutch, Belgium","nl")
        hashMap.put("Dutch, Netherlands","nl")
        hashMap.put("French, Belgium","fr")
        hashMap.put("French, Canada","fr")
        hashMap.put("French, France","fr")
        hashMap.put("French, Switzerland","fr")
        hashMap.put("German, Austria","de")
        hashMap.put("German, Liechtenstein","de")
        hashMap.put("German, Switzerland","de")
        hashMap.put("Italian, Italy","it")
        hashMap.put("Italian, Switzerland","it")
        hashMap.put("Japanese","ja")
        hashMap.put("Korean","ko")
        hashMap.put("Polish","pl")
        hashMap.put("Russian","ru")
        hashMap.put("Spanish","es")
        hashMap.put("Arabic, Egypt","ar")
        hashMap.put("Arabic, Israel","ar")
        hashMap.put("Bulgarian, Bulgaria","bg")
        hashMap.put("Catalan, Spain","ca")
        hashMap.put("Croatian, Croatia","hr")
        hashMap.put("Danish, Denmark","da")
        hashMap.put("Finnish, Finland","fi")
        hashMap.put("Greek, Greece","el")
        hashMap.put("Hebrew, Israel","iw")
        hashMap.put("Hindi, India","hi")
        hashMap.put("Hungarian, Hungary","hu")
        hashMap.put("Indonesian, Indonesia","in")
        hashMap.put("Latvian, Latvia","lv")
        hashMap.put("Lithuanian, Lithuania","lt")
        hashMap.put("Norwegian-Bokmol, Norway","nb")
        hashMap.put("Portuguese, Brazil","pt")
        hashMap.put("Portuguese, Portugal","pt")
        hashMap.put("Romanian, Romania","ro")
        hashMap.put("Serbian","sr")
        hashMap.put("Slovak, Slovakia","sk")
        hashMap.put("Slovenian, Slovenia","sl")
        hashMap.put("Spanish, US","es")
        hashMap.put("Swedish, Sweden","sv")
        hashMap.put("Tagalog, Philippines","tl")
        hashMap.put("Thai, Thailand","th")
        hashMap.put("Turkish, Turkey","tr")
        hashMap.put("Ukrainian, Ukraine","uk")
        hashMap.put("Vietnamese, Vietnam","vi")


        return hashMap;
    }
}