package com.example.myapplication

class LanguageConstantData {
    fun getSupportedLanguageByRecognizer() : HashMap<String, String> {

        var hashMap : HashMap<String, String>
                = HashMap<String, String> ()

        hashMap.put("English, US ","en_US")
        hashMap.put("English, Australia ","en_AU")
        hashMap.put("English, Britain ","en_GB")
        hashMap.put("English, Canada ","en_CA")
        hashMap.put("English, New Zealand ","en_NZ")
        hashMap.put("English, Singapore","en_SG")
        hashMap.put("English, India ","en_IN")
        hashMap.put("English, Ireland ","en_IE")
        hashMap.put("English, Zimbabwe ","en_ZA")
        hashMap.put("German, Germany ","de_DE")
        hashMap.put("Chinese, PRC ","zh_CN")
        hashMap.put("Chinese, Taiwan ","zh_TW")
        hashMap.put("Czech, Czech Republic ","cs_CZ")
        hashMap.put("Dutch, Belgium ","nl_BE")
        hashMap.put("Dutch, Netherlands ","nl_NL")
        hashMap.put("French, Belgium ","fr_BE")
        hashMap.put("French, Canada ","fr_CA")
        hashMap.put("French, France ","fr_FR")
        hashMap.put("French, Switzerland ","fr_CH")
        hashMap.put("German, Austria ","de_AT")
        hashMap.put("German, Liechtenstein ","de_LI")
        hashMap.put("German, Switzerland ","de_CH")
        hashMap.put("Italian, Italy ","it_IT")
        hashMap.put("Italian, Switzerland ","it_CH")
        hashMap.put("Japanese ","ja_JP")
        hashMap.put("Korean ","ko_KR")
        hashMap.put("Polish ","pl_PL")
        hashMap.put("Russian ","ru_RU")
        hashMap.put("Spanish ","es_ES")
        hashMap.put("Arabic, Egypt ","ar_EG")
        hashMap.put("Arabic, Israel ","ar_IL")
        hashMap.put("Bulgarian, Bulgaria ","bg_BG")
        hashMap.put("Catalan, Spain ","ca_ES")
        hashMap.put("Croatian, Croatia ","hr_HR")
        hashMap.put("Danish, Denmark","da_DK")
        hashMap.put("Finnish, Finland ","fi_FI")
        hashMap.put("Greek, Greece ","el_GR")
        hashMap.put("Hebrew, Israel ","iw_IL")
        hashMap.put("Hindi, India ","hi_IN")
        hashMap.put("Hungarian, Hungary ","hu_HU")
        hashMap.put("Indonesian, Indonesia ","in_ID")
        hashMap.put("Latvian, Latvia ","lv_LV")
        hashMap.put("Lithuanian, Lithuania ","lt_LT")
        hashMap.put("Norwegian-Bokmol, Norway","nb_NO")
        hashMap.put("Portuguese, Brazil ","pt_BR")
        hashMap.put("Portuguese, Portugal ","pt_PT")
        hashMap.put("Romanian, Romania ","ro_RO")
        hashMap.put("Serbian ","sr_RS")
        hashMap.put("Slovak, Slovakia ","sk_SK")
        hashMap.put("Slovenian, Slovenia ","sl_SI")
        hashMap.put("Spanish, US ","es_US")
        hashMap.put("Swedish, Sweden ","sv_SE")
        hashMap.put("Tagalog, Philippines ","tl_PH")
        hashMap.put("Thai, Thailand ","th_TH")
        hashMap.put("Turkish, Turkey ","tr_TR")
        hashMap.put("Ukrainian, Ukraine ","uk_UA")
        hashMap.put("Vietnamese, Vietnam ","vi_VN")

        return hashMap;
    }

    fun getSupportedLanguageByGoogle(): HashMap<String, String> {
        var hashMap : HashMap<String, String>
                = HashMap<String, String> ()

        hashMap.put("Afrikaans", "af")
        hashMap.put("Albanian", "sq")
        hashMap.put("Amharic", "am")
        hashMap.put("Arabic", "ar")
        hashMap.put("Armenian", "hy")
        hashMap.put("Azerbaijani", "az")
        hashMap.put("Basque", "eu")
        hashMap.put("Belarusian", "be")
        hashMap.put("Bengali", "bn")
        hashMap.put("Bosnian", "bs")
        hashMap.put("Bulgarian", "bg")
        hashMap.put("Catalan", "ca")
        hashMap.put("Corsican", "co")
        hashMap.put("Croatian", "hr")
        hashMap.put("Czech", "cs")
        hashMap.put("Danish", "da")
        hashMap.put("Dutch", "nl")
        hashMap.put("English", "en")
        hashMap.put("Esperanto", "eo")
        hashMap.put("Estonian", "et")
        hashMap.put("Finnish", "fi")
        hashMap.put("French", "fr")
        hashMap.put("Frisian", "fy")
        hashMap.put("Galician", "gl")
        hashMap.put("Georgian", "ka")
        hashMap.put("German", "de")
        hashMap.put("Greek", "el")
        hashMap.put("Gujarati", "gu")
        hashMap.put("Haitian Creole", "ht")
        hashMap.put("Hausa", "ha")
        hashMap.put("Hawaiian", "")
        hashMap.put("Hebrew", "he")
        hashMap.put("Hindi", "hi")
        hashMap.put("Hmong", "")
        hashMap.put("Hungarian", "hu")
        hashMap.put("Icelandic", "is")
        hashMap.put("Igbo", "ig")
        hashMap.put("Indonesian", "id")
        hashMap.put("Irish", "ga")
        hashMap.put("Italian", "it")
        hashMap.put("Japanese", "ja")
        hashMap.put("Javanese", "jv")
        hashMap.put("Kannada", "kn")
        hashMap.put("Kazakh", "kk")
        hashMap.put("Khmer", "km")
        hashMap.put("Korean", "ko")
        hashMap.put("Kurdish", "ku")
        hashMap.put("Kyrgyz", "ky")
        hashMap.put("Lao", "lo")
        hashMap.put("Latin", "la")
        hashMap.put("Latvian", "lv")
        hashMap.put("Lithuanian", "lt")
        hashMap.put("Luxembourgish", "lb")
        hashMap.put("Macedonian", "mk")
        hashMap.put("Malagasy", "mg")
        hashMap.put("Malay", "ms")
        hashMap.put("Malayalam", "ml")
        hashMap.put("Maltese", "mt")
        hashMap.put("Maori", "mi")
        hashMap.put("Marathi", "mr")
        hashMap.put("Mongolian", "mn")
        hashMap.put("Myanmar (Burmese)", "my")
        hashMap.put("Nepali", "ne")
        hashMap.put("Norwegian", "no")
        hashMap.put("Nyanja (Chichewa)", "ny")
        hashMap.put("Pashto", "ps")
        hashMap.put("Persian", "fa")
        hashMap.put("Polish", "pl")
        hashMap.put("Portuguese", "pt")
        hashMap.put("Punjabi", "pa")
        hashMap.put("Romanian", "ro")
        hashMap.put("Russian", "ru")
        hashMap.put("Samoan", "sm")
        hashMap.put("Scots Gaelic", "gd")
        hashMap.put("Serbian", "sr")
        hashMap.put("Sesotho", "st")
        hashMap.put("Shona", "sn")
        hashMap.put("Sindhi", "sd")
        hashMap.put("Sinhala (Sinhalese)", "si")
        hashMap.put("Slovak", "sk")
        hashMap.put("Slovenian", "sl")
        hashMap.put("Somali", "so")
        hashMap.put("Spanish", "es")
        hashMap.put("Sundanese", "su")
        hashMap.put("Swahili", "sw")
        hashMap.put("Swedish", "sv")
        hashMap.put("Tagalog (Filipino)", "tl")
        hashMap.put("Tajik", "tg")
        hashMap.put("Tamil", "ta")
        hashMap.put("Telugu", "te")
        hashMap.put("Thai", "th")
        hashMap.put("Turkish", "tr")
        hashMap.put("Ukrainian", "uk")
        hashMap.put("Urdu", "ur")
        hashMap.put("Uzbek", "uz")
        hashMap.put("Vietnamese", "vi")
        hashMap.put("Welsh", "cy")
        hashMap.put("Xhosa", "xh")
        hashMap.put("Yiddish", "yi")
        hashMap.put("Yoruba", "yo")
        hashMap.put("Zulu", "zu")

        return hashMap;
    }
}